---
pipeline:
  build:
    image: docker
    commands:
      - docker build -t drone-artifact-deploy:latest ./
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  test:
    image: drone-artifact-deploy:latest
    profile: test
    profiles: ./profiles/
    user: buildagent
