---
pipeline:
  pre_test:
    image: ubuntu:16.04
    commands:
      - apt-get install -y shellcheck
      - shellcheck **/*.sh
  build:
    image: docker
    commands:
      - docker build -t drone-artifact-deploy:latest ./
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  post_test:
    image: drone-artifact-deploy:latest
    profile: test
    profiles: ./profiles/
    user: buildagent
